name: Web CI

on:
  push:
    branches: [main]
    paths:
      - 'apps/web/**'
      - '.github/workflows/web-ci.yml'
  pull_request:
    paths:
      - 'apps/web/**'
      - '.github/workflows/web-ci.yml'

permissions:
  contents: read

concurrency:
  group: web-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Install workspace deps
        run: pnpm install --frozen-lockfile

      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: apps/web/.next/cache
          key: next-cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml', 'apps/web/next.config.js', 'apps/web/package.json') }}

      - name: Typecheck
        run: pnpm --filter @procomp/web run typecheck

      - name: Lint
        run: pnpm --filter @procomp/web run lint

      - name: Build
        working-directory: apps/web
        env:
          NEXT_TELEMETRY_DISABLED: '1'
        run: pnpm build

      - name: Upload .next artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-next-build
          path: apps/web/.next

  deploy:
    name: Deploy to Railway (web)
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && vars.RAILWAY_DEPLOY_WEB == 'true' && secrets.RAILWAY_TOKEN != '' && secrets.RAILWAY_PROJECT_ID != ''
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Link Railway project
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          railway link --project $RAILWAY_PROJECT_ID

      - name: Deploy service web
        working-directory: apps/web
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --service web --detach